VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "cColor"
Attribute VB_GlobalNameSpace = True
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
Option Explicit
Public Property Get AliceBlue() As Long
    AliceBlue = &HFFF0F8FF
End Property

Public Property Get AntiqueWhite() As Long
    AntiqueWhite = &HFFFAEBD7
End Property

Public Property Get Aqua() As Long
    Aqua = &HFF00FFFF
End Property

Public Property Get Aquamarine() As Long
    Aquamarine = &HFF7FFFD4
End Property

Public Property Get Azure() As Long
    Azure = &HFFF0FFFF
End Property

Public Property Get Beige() As Long
    Beige = &HFFF5F5DC
End Property

Public Property Get Bisque() As Long
    Bisque = &HFFFFE4C4
End Property

Public Property Get Black() As Long
    Black = &HFF000000
End Property

Public Property Get BlanchedAlmond() As Long
    BlanchedAlmond = &HFFFFEBCD
End Property

Public Property Get Blue() As Long
    Blue = &HFF0000FF
End Property

Public Property Get BlueViolet() As Long
    BlueViolet = &HFF8A2BE2
End Property

Public Property Get Brown() As Long
    Brown = &HFFA52A2A
End Property

Public Property Get BurlyWood() As Long
    BurlyWood = &HFFDEB887
End Property

Public Property Get CadetBlue() As Long
    CadetBlue = &HFF5F9EA0
End Property

Public Property Get Chartreuse() As Long
    Chartreuse = &HFF7FFF00
End Property

Public Property Get Chocolate() As Long
    Chocolate = &HFFD2691E
End Property

Public Property Get Coral() As Long
    Coral = &HFFFF7F50
End Property

Public Property Get CornflowerBlue() As Long
    CornflowerBlue = &HFF6495ED
End Property

Public Property Get Cornsilk() As Long
    Cornsilk = &HFFFFF8DC
End Property

Public Property Get Crimson() As Long
    Crimson = &HFFDC143C
End Property

Public Property Get Cyan() As Long
    Cyan = &HFF00FFFF
End Property

Public Property Get DarkBlue() As Long
    DarkBlue = &HFF00008B
End Property

Public Property Get DarkCyan() As Long
    DarkCyan = &HFF008B8B
End Property

Public Property Get DarkGoldenrod() As Long
    DarkGoldenrod = &HFFB8860B
End Property

Public Property Get DarkGray() As Long
    DarkGray = &HFFA9A9A9
End Property

Public Property Get DarkGreen() As Long
    DarkGreen = &HFF006400
End Property

Public Property Get DarkKhaki() As Long
    DarkKhaki = &HFFBDB76B
End Property

Public Property Get DarkMagenta() As Long
    DarkMagenta = &HFF8B008B
End Property

Public Property Get DarkOliveGreen() As Long
    DarkOliveGreen = &HFF556B2F
End Property

Public Property Get DarkOrange() As Long
    DarkOrange = &HFFFF8C00
End Property

Public Property Get DarkOrchid() As Long
    DarkOrchid = &HFF9932CC
End Property

Public Property Get DarkRed() As Long
    DarkRed = &HFF8B0000
End Property

Public Property Get DarkSalmon() As Long
    DarkSalmon = &HFFE9967A
End Property

Public Property Get DarkSeaGreen() As Long
    DarkSeaGreen = &HFF8FBC8B
End Property

Public Property Get DarkSlateBlue() As Long
    DarkSlateBlue = &HFF483D8B
End Property

Public Property Get DarkSlateGray() As Long
    DarkSlateGray = &HFF2F4F4F
End Property

Public Property Get DarkTurquoise() As Long
    DarkTurquoise = &HFF00CED1
End Property

Public Property Get DarkViolet() As Long
    DarkViolet = &HFF9400D3
End Property

Public Property Get DeepPink() As Long
    DeepPink = &HFFFF1493
End Property

Public Property Get DeepSkyBlue() As Long
    DeepSkyBlue = &HFF00BFFF
End Property

Public Property Get DimGray() As Long
    DimGray = &HFF696969
End Property

Public Property Get DodgerBlue() As Long
    DodgerBlue = &HFF1E90FF
End Property

Public Property Get Firebrick() As Long
    Firebrick = &HFFB22222
End Property

Public Property Get FloralWhite() As Long
    FloralWhite = &HFFFFFAF0
End Property

Public Property Get ForestGreen() As Long
    ForestGreen = &HFF228B22
End Property

Public Property Get Fuchsia() As Long
    Fuchsia = &HFFFF00FF
End Property

Public Property Get Gainsboro() As Long
    Gainsboro = &HFFDCDCDC
End Property

Public Property Get GhostWhite() As Long
    GhostWhite = &HFFF8F8FF
End Property

Public Property Get Gold() As Long
    Gold = &HFFFFD700
End Property

Public Property Get Goldenrod() As Long
    Goldenrod = &HFFDAA520
End Property

Public Property Get Gray() As Long
    Gray = &HFF808080
End Property

Public Property Get Green() As Long
    Green = &HFF008000
End Property

Public Property Get GreenYellow() As Long
    GreenYellow = &HFFADFF2F
End Property

Public Property Get Honeydew() As Long
    Honeydew = &HFFF0FFF0
End Property

Public Property Get HotPink() As Long
    HotPink = &HFFFF69B4
End Property

Public Property Get IndianRed() As Long
    IndianRed = &HFFCD5C5C
End Property

Public Property Get Indigo() As Long
    Indigo = &HFF4B0082
End Property

Public Property Get Ivory() As Long
    Ivory = &HFFFFFFF0
End Property

Public Property Get Khaki() As Long
    Khaki = &HFFF0E68C
End Property

Public Property Get Lavender() As Long
    Lavender = &HFFE6E6FA
End Property

Public Property Get LavenderBlush() As Long
    LavenderBlush = &HFFFFF0F5
End Property

Public Property Get LawnGreen() As Long
    LawnGreen = &HFF7CFC00
End Property

Public Property Get LemonChiffon() As Long
    LemonChiffon = &HFFFFFACD
End Property

Public Property Get LightBlue() As Long
    LightBlue = &HFFADD8E6
End Property

Public Property Get LightCoral() As Long
    LightCoral = &HFFF08080
End Property

Public Property Get LightCyan() As Long
    LightCyan = &HFFE0FFFF
End Property

Public Property Get LightGoldenrodYellow() As Long
    LightGoldenrodYellow = &HFFFAFAD2
End Property

Public Property Get LightGray() As Long
    LightGray = &HFFD3D3D3
End Property

Public Property Get LightGreen() As Long
    LightGreen = &HFF90EE90
End Property

Public Property Get LightPink() As Long
    LightPink = &HFFFFB6C1
End Property

Public Property Get LightSalmon() As Long
    LightSalmon = &HFFFFA07A
End Property

Public Property Get LightSeaGreen() As Long
    LightSeaGreen = &HFF20B2AA
End Property

Public Property Get LightSkyBlue() As Long
    LightSkyBlue = &HFF87CEFA
End Property

Public Property Get LightSlateGray() As Long
    LightSlateGray = &HFF778899
End Property

Public Property Get LightSteelBlue() As Long
    LightSteelBlue = &HFFB0C4DE
End Property

Public Property Get LightYellow() As Long
    LightYellow = &HFFFFFFE0
End Property

Public Property Get Lime() As Long
    Lime = &HFF00FF00
End Property

Public Property Get LimeGreen() As Long
    LimeGreen = &HFF32CD32
End Property

Public Property Get Linen() As Long
    Linen = &HFFFAF0E6
End Property

Public Property Get Magenta() As Long
    Magenta = &HFFFF00FF
End Property

Public Property Get Maroon() As Long
    Maroon = &HFF800000
End Property

Public Property Get MediumAquamarine() As Long
    MediumAquamarine = &HFF66CDAA
End Property

Public Property Get MediumBlue() As Long
    MediumBlue = &HFF0000CD
End Property

Public Property Get MediumOrchid() As Long
    MediumOrchid = &HFFBA55D3
End Property

Public Property Get MediumPurple() As Long
    MediumPurple = &HFF9370DB
End Property

Public Property Get MediumSeaGreen() As Long
    MediumSeaGreen = &HFF3CB371
End Property

Public Property Get MediumSlateBlue() As Long
    MediumSlateBlue = &HFF7B68EE
End Property

Public Property Get MediumSpringGreen() As Long
    MediumSpringGreen = &HFF00FA9A
End Property

Public Property Get MediumTurquoise() As Long
    MediumTurquoise = &HFF48D1CC
End Property

Public Property Get MediumVioletRed() As Long
    MediumVioletRed = &HFFC71585
End Property

Public Property Get MidnightBlue() As Long
    MidnightBlue = &HFF191970
End Property

Public Property Get MintCream() As Long
    MintCream = &HFFF5FFFA
End Property

Public Property Get MistyRose() As Long
    MistyRose = &HFFFFE4E1
End Property

Public Property Get Moccasin() As Long
    Moccasin = &HFFFFE4B5
End Property

Public Property Get NavajoWhite() As Long
    NavajoWhite = &HFFFFDEAD
End Property

Public Property Get Navy() As Long
    Navy = &HFF000080
End Property

Public Property Get OldLace() As Long
    OldLace = &HFFFDF5E6
End Property

Public Property Get Olive() As Long
    Olive = &HFF808000
End Property

Public Property Get OliveDrab() As Long
    OliveDrab = &HFF6B8E23
End Property

Public Property Get Orange() As Long
    Orange = &HFFFFA500
End Property

Public Property Get OrangeRed() As Long
    OrangeRed = &HFFFF4500
End Property

Public Property Get Orchid() As Long
    Orchid = &HFFDA70D6
End Property

Public Property Get PaleGoldenrod() As Long
    PaleGoldenrod = &HFFEEE8AA
End Property

Public Property Get PaleGreen() As Long
    PaleGreen = &HFF98FB98
End Property

Public Property Get PaleTurquoise() As Long
    PaleTurquoise = &HFFAFEEEE
End Property

Public Property Get PaleVioletRed() As Long
    PaleVioletRed = &HFFDB7093
End Property

Public Property Get PapayaWhip() As Long
    PapayaWhip = &HFFFFEFD5
End Property

Public Property Get PeachPuff() As Long
    PeachPuff = &HFFFFDAB9
End Property

Public Property Get Peru() As Long
    Peru = &HFFCD853F
End Property

Public Property Get Pink() As Long
    Pink = &HFFFFC0CB
End Property

Public Property Get Plum() As Long
    Plum = &HFFDDA0DD
End Property

Public Property Get PowderBlue() As Long
    PowderBlue = &HFFB0E0E6
End Property

Public Property Get Purple() As Long
    Purple = &HFF800080
End Property

Public Property Get Red() As Long
    Red = &HFFFF0000
End Property

Public Property Get RosyBrown() As Long
    RosyBrown = &HFFBC8F8F
End Property

Public Property Get RoyalBlue() As Long
    RoyalBlue = &HFF4169E1
End Property

Public Property Get SaddleBrown() As Long
    SaddleBrown = &HFF8B4513
End Property

Public Property Get Salmon() As Long
    Salmon = &HFFFA8072
End Property

Public Property Get SandyBrown() As Long
    SandyBrown = &HFFF4A460
End Property

Public Property Get SeaGreen() As Long
    SeaGreen = &HFF2E8B57
End Property

Public Property Get SeaShell() As Long
    SeaShell = &HFFFFF5EE
End Property

Public Property Get Sienna() As Long
    Sienna = &HFFA0522D
End Property

Public Property Get Silver() As Long
    Silver = &HFFC0C0C0
End Property

Public Property Get SkyBlue() As Long
    SkyBlue = &HFF87CEEB
End Property

Public Property Get SlateBlue() As Long
    SlateBlue = &HFF6A5ACD
End Property

Public Property Get SlateGray() As Long
    SlateGray = &HFF708090
End Property

Public Property Get Snow() As Long
    Snow = &HFFFFFAFA
End Property

Public Property Get SpringGreen() As Long
    SpringGreen = &HFF00FF7F
End Property

Public Property Get SteelBlue() As Long
    SteelBlue = &HFF4682B4
End Property

Public Property Get Tan() As Long
    Tan = &HFFD2B48C
End Property

Public Property Get Teal() As Long
    Teal = &HFF008080
End Property

Public Property Get Thistle() As Long
    Thistle = &HFFD8BFD8
End Property

Public Property Get Tomato() As Long
    Tomato = &HFFFF6347
End Property

Public Property Get Transparent() As Long
    Transparent = &HFFFFFF
End Property

Public Property Get Turquoise() As Long
    Turquoise = &HFF40E0D0
End Property

Public Property Get Violet() As Long
    Violet = &HFFEE82EE
End Property

Public Property Get Wheat() As Long
    Wheat = &HFFF5DEB3
End Property

Public Property Get White() As Long
    White = &HFFFFFFFF
End Property

Public Property Get WhiteSmoke() As Long
    WhiteSmoke = &HFFF5F5F5
End Property

Public Property Get Yellow() As Long
    Yellow = &HFFFFFF00
End Property

Public Property Get YellowGreen() As Long
    YellowGreen = &HFF9ACD32
End Property

Public Function FromARGB(ByVal A As Byte, ByVal R As Byte, ByVal G As Byte, ByVal B As Byte) As Long
    FromARGB = ARGB(A, R, G, B)
End Function

Public Function GetAlpha(ByVal nColor As Long) As Byte
    Dim A As Byte
    CopyMemory ByVal VarPtr(A), ByVal VarPtr(nColor) + 3, 1
    GetAlpha = A
End Function

Public Function GetRed(ByVal nColor As Long) As Byte
    Dim R As Byte
    CopyMemory ByVal VarPtr(R), ByVal VarPtr(nColor) + 2, 1
    GetRed = R
End Function

Public Function GetGreen(ByVal nColor As Long) As Byte
    Dim G As Byte
    CopyMemory ByVal VarPtr(G), ByVal VarPtr(nColor) + 1, 1
    GetGreen = G
End Function

Public Function GetBlue(ByVal nColor As Long) As Byte
    Dim B As Byte
    CopyMemory ByVal VarPtr(B), ByVal VarPtr(nColor), 1
    GetBlue = B
End Function

Public Function SetBrightness(ByVal nColor As Long, ByVal Offset As Single) As Long
    Dim A As Byte, R As Byte, G As Byte, B As Byte
    
    A = GetAlpha(nColor)
    R = GetRed(nColor)
    G = GetGreen(nColor)
    B = GetBlue(nColor)
    
    Offset = IIf(Offset < -1, -1, IIf(Offset > 1, 1, Offset))
    
    If Offset < 0 Then
        R = R + R * Offset
        G = G + G * Offset
        B = B + B * Offset
    Else
        R = R + (255 - R) * Offset
        G = G + (255 - G) * Offset
        B = B + (255 - B) * Offset
    End If

    SetBrightness = ARGB(A, R, G, B)
End Function

Public Function SetAlpha(ByVal nColor As Long, ByVal Offset As Single) As Long
    Dim A As Byte, R As Byte, G As Byte, B As Byte
    
    A = GetAlpha(nColor)
    R = GetRed(nColor)
    G = GetGreen(nColor)
    B = GetBlue(nColor)
    
    Offset = IIf(Offset < -1, -1, IIf(Offset > 1, 1, Offset))
    
    If Offset < 0 Then
        A = A + A * Offset
    Else
        A = A + (255 - A) * Offset
    End If
    
    SetAlpha = ARGB(A, R, G, B)
End Function

